version: '3'
services:
  web:
    image: null-cell/just_werify_it:dev
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - FLAG=frictf{7he_fl4g_1s_4lways_h3re}
        - ENV_PASSWORD=super_secret_password_that_is_not_pushed_to_github_1337
      target: production
    ports:
      - "8080:3000"
    networks:
      - web
    command: npm run dev
    volumes:
      - ./:/app
networks:
  web:
