FROM python:3.9-slim

ENV FLAG=frictf{xss_is_fun_51596b5fc1bf}

COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt

USER root
COPY . /app
RUN chown -R 1337:1337 /app

CMD [ "waitress-serve", "--port=8000", "--call", "src:create_app"]
