services:
  redis:
    container_name: redis
    image: "redis:6-alpine"

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - FLAG=frictf{xss_is_fun_hehe}
    depends_on:
      - redis
    ports:
      - "80:8080"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - redis
