version: '3'
services:
  web:
    image: aljazmedic/webburpdemo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FLAG=frictf{d0nt_7rust_th3_cl13nt}
    ports:
      - "3000:3000"
    networks:
      - web
networks:
  web: